#!/bin/bash
source "$(dirname "$0")/commands/utils.sh"
source "$(dirname "$0")/commands/styles.sh"
source "$(dirname "$0")/commands/build.sh"
source "$(dirname "$0")/commands/clean.sh"
source "$(dirname "$0")/commands/run.sh"

# Main script execution starts here
if [ $# -eq 0 ]; then
    separator
    error "Invalid command. Usage: $0 [build|clean|run <program_name>]"
    separator
    exit 1
fi

# Parse the command
case "$1" in
    build)
        build
        ;;
    clean)
        clean
        ;;
    run)
        shift
        run "$1"
        ;;
    *)
        separator
        error "Invalid command. Usage: $0 [build|clean|run <program_name>]"
        separator
        exit 1
        ;;
esac